AWSTemplateFormatVersion: 2010-09-09
Description: >
  Scalable architecture project - EC2 (AutoScaling), RDS, and S3-triggered Lambda.

Parameters:
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for web instances (e.g., Amazon Linux 2)

  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
    Description: EC2 instance type for web servers

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Existing EC2 Key Pair name for SSH access

  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Public subnets (created by Terraform) for the Auto Scaling Group

  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private subnets (created by Terraform) for RDS (must be in 2 AZs)

  EC2SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for EC2 instances (from Terraform)

  RDSSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for RDS (from Terraform)

  DBName:
    Type: String
    Default: appdb
    Description: Database name for RDS

  DBUser:
    Type: String
    Default: appuser
    MinLength: 1
    MaxLength: 16
    Description: Master username for RDS

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    Description: Master password for RDS

  UploadsBucketName:
    Type: String
    Description: Globally unique S3 bucket name for logging uploads

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for the load balancer and target group

Resources:
  ################################################
  # IAM Role for Lambda
  ################################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /

  ################################################
  # Lambda Function to log S3 uploads
  ################################################
  UploadLogFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      Code:
        ZipFile: |
          import json
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              logger.info("Received event: %s", json.dumps(event))
              for record in event.get("Records", []):
                  bucket = record["s3"]["bucket"]["name"]
                  key = record["s3"]["object"]["key"]
                  size = record["s3"]["object"].get("size", 0)
                  logger.info(
                      "New S3 object - bucket=%s, key=%s, size=%s bytes",
                      bucket, key, size
                  )
              return {"statusCode": 200, "body": "OK"}

  ################################################
  # Permission for S3 to invoke the Lambda
  ################################################
  UploadLogPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UploadLogFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${UploadsBucketName}

  ################################################
  # S3 bucket that triggers the Lambda on upload
  ################################################
  UploadsBucket:
    Type: AWS::S3::Bucket
    DependsOn: UploadLogPermission
    Properties:
      BucketName: !Ref UploadsBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt UploadLogFunction.Arn

  ################################################
  # RDS Subnet Group (uses 2 private subnets)
  ################################################
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Private subnets for RDS
      SubnetIds: !Ref PrivateSubnetIds

  ################################################
  # RDS Database Instance
  ################################################
  WebAppDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      EngineVersion: '8.0'
      DBInstanceClass: db.t3.micro
      AllocatedStorage: '20'
      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref RDSSecurityGroupId
      DBSubnetGroupName: !Ref DbSubnetGroup
      MultiAZ: false
      PubliclyAccessible: false
      DeletionProtection: false
      BackupRetentionPeriod: 0

  ################################################
  # Launch Template for web EC2 instances
  ################################################
  WebAppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref EC2SecurityGroupId
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y || dnf update -y
            yum install -y httpd || dnf install -y httpd
            systemctl enable httpd

            cat > /var/www/html/index.html << 'EOF'
            <html>
              <head>
                <title>Course Project Web App</title>
              </head>
              <body>
                <h1>Welcome to my Course Project Web Application</h1>
                <p>EC2 instance launched via CloudFormation Auto Scaling Group.</p>
              </body>
            </html>
            EOF

            systemctl start httpd

  ################################################
  # Application Load Balancer + Target Group
  ################################################
  WebAppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: webapp-alb
      Subnets: !Ref PublicSubnetIds
      SecurityGroups:
        - !Ref EC2SecurityGroupId
      Scheme: internet-facing
      Type: application

  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      Matcher:
        HttpCode: 200

  WebAppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref WebAppLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebAppTargetGroup

  ################################################
  # Auto Scaling Group for EC2 web servers
  ################################################
  WebAppAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref PublicSubnetIds
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'
      LaunchTemplate:
        LaunchTemplateId: !Ref WebAppLaunchTemplate
        Version: !GetAtt WebAppLaunchTemplate.LatestVersionNumber
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      TargetGroupARNs:
        - !Ref WebAppTargetGroup

Outputs:
  RdsEndpoint:
    Description: RDS database endpoint (for app DB connection)
    Value: !GetAtt WebAppDB.Endpoint.Address

  S3UploadsBucketName:
    Description: S3 bucket used for Lambda logging of uploads
    Value: !Ref UploadsBucket

  LambdaFunctionName:
    Description: Name of the Lambda function that logs S3 uploads
    Value: !Ref UploadLogFunction

  AutoScalingGroupName:
    Description: Name of the Auto Scaling Group for web EC2 instances
    Value: !Ref WebAppAutoScalingGroup
